version: "3"
services:
  client:
    build: ./client
    volumes:
      - ./client:/app
    ports:
      - "8080:8080"
    links:
      - server
  server:
    build: ./server
    volumes:
      - ./server:/app
    ports:
      - "8081:8081"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
        - "27017:27017"